### ISSUE TITLE
Terraform v0.12 support?

### ISSUE THREAD

**Issue by dpfeif** [Mongey/terraform-provider-ksql#6]
Hi,

I tried to get the plugin v0.0.1 to work in [Atlantis `v0.8.3`](https://hub.docker.com/r/runatlantis/atlantis/tags) (Terraform `v0.12.3`)
> Error: Failed to instantiate provider "ksql" to obtain schema: Incompatible API version with plugin. Plugin version: 4, Client versions: [5]

I then tried building the plugin from master on MacOsX `18.7.0 Darwin` but got:
> Error: Failed to instantiate provider "ksql" to obtain schema: fork/exec /home/atlantis/.terraform.d/plugins/linux_amd64/terraform-provider-ksql: exec format error

Is the plugin supposed to work with Terraform ≥ v0.12?

Thank you for sharing this great work.

**Comment by Mongey** [comment]
Hi @dpfeif can you try the [latest release, v0.0.2](https://github.com/Mongey/terraform-provider-ksql/releases/tag/v0.0.2) It should work with 0.12

**Comment by dpfeif** [comment]
Hi @Mongey, v0.0.2 is integrating flawlessly with our setup in Terraform 0.12.3.
Thanks a lot!
