### ISSUE TITLE
Binary Release

### ISSUE THREAD

**Issue by tzzh** [Mongey/terraform-provider-ksql#7]
Hey @Mongey,
Thanks for your kafka plugins they are amazing 👍 
Would it be possible to add compiled binaries for this plugin in the release as well (same as you have for eg kafka-connect https://github.com/Mongey/terraform-provider-kafka-connect/releases/download/v0.2.0/terraform-provider-kafka-connect_0.2.0_linux_amd64.tar.gz)
Cheers

**Comment by Mongey** [comment]
🤗 thanks @tzzh . Looks like there was an issue with releasing the v0.0.2 release, I've re-released, and the linux + osx binaries are in the release
